source 'https://mirrors.bfsu.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/TokiPods/specs.git'

platform :ios, '9.0'

target 'TKMAccountModule_Example' do
  pod 'TKMAccountModule', :path => '../'
  
  pod 'TKMInitializeModule'

  target 'TKMAccountModule_Tests' do
    inherit! :search_paths

    
  end
end
