source 'https://github.com/TokiPods/specs.git'

platform :ios, '9.0'

target 'TKMAccountModule_Example' do
  pod 'TKMAccountModule', :path => '../'

  target 'TKMAccountModule_Tests' do
    inherit! :search_paths

    
  end
end
